integrations:
  stable-diffusion-v2-1-base-diffusers:
    type: dataset
    ref: paperspace/dsq06vmkcmyn3se:latest
  stable-diffusion-classic:
    type: dataset
    ref: paperspace/ds7isjs9l5q2m3j:latest
  stable-diffusion-v2-1:
    type: dataset
    ref: paperspace/dsq9ftjo24ou0ji:latest
  stable-diffusion-diffusers-v2:
    type: dataset
    ref: paperspace/dsip85mcg4dhe8e:latest
  stable-diffusion-classic-v2:
    type: dataset
    ref: paperspace/dsk2jb016aes4uq:latest
  stable-diffusion-diffusers:
    type: dataset
    ref: paperspace/dsj70qb5x6u9stk:latest
  stable-diffusion-xl:
    type: dataset
    ref: paperspace/dseg53659wn0e6p:latest    
